# Generated by Django 5.0.1 on 2024-02-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_name_customer_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ShippingAddress',
            new_name='shipping_address',
        ),
    ]
