# Generated by Django 5.0.2 on 2024-03-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_description_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
