# Generated by Django 5.0.2 on 2024-03-03 10:09

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=200, null=True, verbose_name=store.models.Customer),
        ),
    ]
