# Generated by Django 5.0.2 on 2024-03-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
