# Generated by Django 5.0.2 on 2024-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_order_shipping_address_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
