# Generated by Django 5.0.3 on 2024-03-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_cancel_date_order_refund_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='connectivity_technology',
        ),
    ]
