# Generated by Django 5.0.3 on 2024-03-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_size_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='connectivity_technology',
            new_name='color',
        ),
    ]
