# Generated by Django 5.0.3 on 2024-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_color_product_connectivity_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='connectivity_technology',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
