# Generated by Django 5.0.1 on 2024-03-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_description_en_product_description_zh_hant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
