# Generated by Django 5.0.1 on 2024-03-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_imgae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgae',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
