# Generated by Django 5.0.1 on 2024-03-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_imgae_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imgae',
            new_name='Image',
        ),
    ]
