# Generated by Django 5.0.3 on 2024-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_sale',
            field=models.BooleanField(default=False, verbose_name='best_sale'),
        ),
    ]
