# Generated by Django 5.0.3 on 2024-04-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_product_best_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover_image'),
        ),
    ]
